#!/usr/bin/env python3
"""
Generate the per-SDK build inputs from a directory of vendor aarch64 ELFs:

  src/gen/x18_<ident>.h   x18 patch tables (via x18_patch.py)
  src/gen/images.S        vendor ELFs embedded with .incbin
  src/gen/images.h        table describing the embedded images
  src/gen/exports.S       one tail-branch trampoline per exported C function
  src/gen/exports.txt     exported-symbols list for the linker

usage: gen_build.py <vendor-lib-dir>
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GEN = os.path.join(ROOT, "src", "gen")
READELF = "/opt/homebrew/opt/binutils/bin/greadelf"

# (glob-ish prefix, ident, plugin?) in load order. Plugins are only mapped when
# the SDK dlopen()s them.
IMAGES = [
    ("libliquid.so", "liquid", False),
    ("libhtraapi.so", "htraapi", False),
    ("libDigitalSigDemod.so", "demod", True),
]


def find(libdir, prefix):
    names = sorted(n for n in os.listdir(libdir) if n.startswith(prefix))
    return os.path.join(libdir, names[-1]) if names else None


def c_exports(path):
    out = subprocess.run([READELF, "--dyn-syms", "-W", path], capture_output=True, text=True,
                         check=True).stdout
    names = []
    for line in out.splitlines():
        f = line.split()
        if len(f) >= 8 and f[3] == "FUNC" and f[4] in ("GLOBAL", "WEAK") and f[6] != "UND":
            n = f[7].split("@")[0]
            if re.match(r"^[A-Za-z][A-Za-z0-9_]*$", n):  # extern "C", not _init/_Z...
                names.append(n)
    return names


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    libdir = os.path.abspath(sys.argv[1])
    os.makedirs(GEN, exist_ok=True)

    images = []
    for prefix, ident, plugin in IMAGES:
        path = find(libdir, prefix)
        if not path:
            if plugin:
                continue
            sys.exit(f"missing {prefix} in {libdir}")
        subprocess.run([sys.executable, os.path.join(HERE, "x18_patch.py"), path, ident,
                        os.path.join(GEN, f"x18_{ident}.h")], check=True)
        images.append((path, ident, plugin, prefix))

    with open(os.path.join(GEN, "images.S"), "w") as f:
        f.write("/* Generated by tools/gen_build.py -- vendor ELF images. */\n")
        f.write("    .section __DATA,__const\n")
        for path, ident, _, _ in images:
            f.write(f"    .p2align 4\n    .globl _img_{ident}_start\n_img_{ident}_start:\n")
            f.write(f'    .incbin "{path}"\n')
            f.write(f"    .globl _img_{ident}_end\n_img_{ident}_end:\n")

    with open(os.path.join(GEN, "images.h"), "w") as f:
        f.write("/* Generated by tools/gen_build.py -- do not edit. */\n")
        f.write("#include \"../elf_loader.h\"\n")
        for _, ident, _, _ in images:
            f.write(f'#include "x18_{ident}.h"\n')
            f.write(f"extern const uint8_t img_{ident}_start[], img_{ident}_end[];\n")
        f.write("struct embedded_image {\n    const char *name;\n    const uint8_t *start, *end;\n"
                "    const struct x18_patch *patches;\n    size_t npatches;\n    int plugin;\n};\n")
        f.write("static const struct embedded_image embedded_images[] = {\n")
        for path, ident, plugin, prefix in images:
            f.write(f'    {{"{prefix}", img_{ident}_start, img_{ident}_end, {ident}_x18,\n'
                    f"     sizeof {ident}_x18 / sizeof {ident}_x18[0], {int(plugin)}}},\n")
        f.write("};\nstatic const size_t embedded_image_count = "
                "sizeof embedded_images / sizeof embedded_images[0];\n")

    # Core images only; later images take precedence for duplicate names.
    exports, seen = [], set()
    for path, ident, plugin, _ in reversed(images):
        if plugin:
            continue
        for n in c_exports(path):
            if n not in seen:
                seen.add(n)
                exports.append(n)
    exports.sort()

    with open(os.path.join(GEN, "exports.S"), "w") as f:
        f.write("/* Generated by tools/gen_build.py -- API trampolines. */\n")
        f.write("    .section __DATA,__data\n    .p2align 3\n    .globl _htra_export_slots\n"
                "_htra_export_slots:\n")
        for i, _ in enumerate(exports):
            f.write(f"_htra_slot_{i}:\n    .quad 0\n")
        f.write("\n    .section __TEXT,__cstring\n")
        for i, n in enumerate(exports):
            f.write(f'Lname_{i}:\n    .asciz "{n}"\n')
        f.write("\n    .section __DATA,__const\n    .p2align 3\n    .globl _htra_export_names\n"
                "_htra_export_names:\n")
        for i, _ in enumerate(exports):
            f.write(f"    .quad Lname_{i}\n")
        f.write(f"    .p2align 2\n    .globl _htra_export_count\n_htra_export_count:\n"
                f"    .long {len(exports)}\n")
        f.write("\n    .text\n    .p2align 2\n")
        for i, n in enumerate(exports):
            f.write(f"    .globl _{n}\n_{n}:\n"
                    f"    adrp x16, _htra_slot_{i}@PAGE\n"
                    f"    ldr x16, [x16, _htra_slot_{i}@PAGEOFF]\n"
                    f"    br x16\n")

    with open(os.path.join(GEN, "exports.txt"), "w") as f:
        for n in exports:
            f.write(f"_{n}\n")
    print(f"embedded {len(images)} image(s); {len(exports)} API exports")


if __name__ == "__main__":
    main()
